telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D0128>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D0860>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D9860>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D9C50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=1 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D9BE0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D9EF0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D9A90>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D9898>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=2 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D9E48>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038F91D0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038F92E8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038F94E0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=3 max_retries=-1
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000381EFD0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003831748>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383E748>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383EB38>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=1 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383EAC8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383EDA0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383ED68>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383EB70>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=2 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383ED30>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385B0B8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385B1D0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385B390>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=3 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385B2E8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385B8D0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385B9E8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385BBA8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=4 max_retries=-1
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000389DFD0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038B1748>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BE748>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BEB38>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=1 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BEAC8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038DB0B8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BEB00>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BEC50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=2 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BED30>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038DB358>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038DB470>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038DB630>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=3 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038DB588>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038DBB70>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038DBC88>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038DBE48>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=4 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000381FF60>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038316D8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383E6D8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383EAC8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=1 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383EA58>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383EF98>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383EA90>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383EBE0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=2 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000383ECC0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385B2E8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385B400>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385B5C0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=3 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385B518>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385BB00>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385BC18>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000385BDD8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=4 max_retries=-1
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038B3128>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038B3860>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BA860>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BAC50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=1 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BABE0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D81D0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D82E8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BAEF0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=2 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BAE48>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BAB38>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038B3780>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8748>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=3 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D86D8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8C88>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8DA0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8F60>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=4 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E80F0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8518>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E85C0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8940>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=5 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8DD8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8B70>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8898>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8710>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=6 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8FD0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BAB70>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BAC88>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BAEF0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=7 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8198>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8B70>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8C88>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8E48>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=8 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E80B8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038F93C8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8F28>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8EF0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=9 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8A20>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8048>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8278>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8828>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=10 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8C50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D85F8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D84A8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D87B8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=11 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8780>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8C18>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8F98>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D85C0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=12 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8A58>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BAB70>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BAD68>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D80F0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=13 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8320>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8EB8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8E80>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8CF8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=14 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8358>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8AC8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8208>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8898>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=15 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E83C8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8780>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8550>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8F60>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=16 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E82E8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038BADA0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038B3780>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000000000389FF98>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=17 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8B38>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8BE0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8978>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E85C0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=18 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8EB8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8C50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038E8358>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot705952373:AAHroSOXqrgr0dySvq2oZxpHVavWwTL956g/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000000038D8470>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=19 max_retries=-1
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "ephem_bot.py", line 53, in planet_go
    planet_date = ephem.planet(today_st)
AttributeError: module 'ephem' has no attribute 'planet'
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "ephem_bot.py", line 53, in planet_go
    planet_date = ephem.planet(today_st)
AttributeError: module 'ephem' has no attribute 'planet'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "ephem_bot.py", line 53, in planet_go
    planet_date = ephem.planet(today_st)
AttributeError: module 'ephem' has no attribute 'planet'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "ephem_bot.py", line 69, in planet_go
    update.message.reply_text(result)
UnboundLocalError: local variable 'result' referenced before assignment
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "ephem_bot.py", line 69, in planet_go
    update.message.reply_text(result)
UnboundLocalError: local variable 'result' referenced before assignment
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "ephem_bot.py", line 69, in planet_go
    print (result)
UnboundLocalError: local variable 'result' referenced before assignment
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "ephem_bot.py", line 69, in planet_go
    print (result)
UnboundLocalError: local variable 'result' referenced before assignment
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "ephem_bot.py", line 69, in planet_go
    print (result)
UnboundLocalError: local variable 'result' referenced before assignment
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\maria.rodionova\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "ephem_bot.py", line 69, in planet_go
    print (result)
UnboundLocalError: local variable 'result' referenced before assignment
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
